name: Another Blog Attempt
markdown: kramdown
highlighter: rouge
authors:
  John:
    name: John Bradley
    display_name: John
    email: johnbradley436@gmail.com
    github: johnbradley436
permalink: /blog/:year/:month/:day/:title
  

theme: jekyll-theme-midnight
